### ISSUE TITLE
Response failure, please try again.

### ISSUE THREAD

**Issue by yahao-li** [obiscr/ChatGPT#288] opened 2023-10-20 05:21 UTC
Response failure, please try again. Error message: {"cf_details":"Something went wrong. Please contact Support.", "type":"dc"}

**Comment by Miofly** [comment] 2023-10-20 05:44
same error

**Comment by obiscr** [comment] 2023-10-20 06:22
Hi, this issue was a duplicate of #287  and now looks to be fixed. Could you try it again?

**Comment by dalaverd** [comment] 2023-10-20 16:31
I still have this issue since yesterday

**Comment by obiscr** [comment] 2023-10-23 09:13
This issue has been fixed, thanks.

**Closed** 2023-10-23 09:13 UTC

**Comment by dalaverd** [comment] 2023-10-23 14:44
![image](https://github.com/obiscr/ChatGPT/assets/4228254/57eff052-6d7c-404b-9cca-d9428b1c6279)
